### ISSUE TITLE
Error installing an npm library with jspm

### ISSUE THREAD

**Issue by fdhenard** [jspm/npm#103]
I'm posting this here, partly because I'm not sure if the problem is with jspm-npm or if it's with the library I'm trying to install.  I've also posted [this issue](https://github.com/quri/react-bootstrap-datetimepicker/issues/112) (wondering if it's a problem with the library and not jspm), and [this SO question](http://stackoverflow.com/q/33158793/59439).

I'm fairly new to jspm and stack, but I'm having trouble installing react-bootstrap-datetimepicker, but not other libraries.

```
$ jspm install npm:react-bootstrap-datetimepicker
Password:
     Looking up npm:react-bootstrap-datetimepicker
     Updating registry cache...
     Downloading npm:react-bootstrap-datetimepicker@0.0.21
     Looking up npm:babel-runtime
     Looking up npm:classnames
     Looking up npm:moment
     Looking up npm:react-bootstrap
     Looking up npm:react
     Downloading npm:classnames@2.1.5
     Downloading npm:react-bootstrap@0.16.1
     Downloading npm:moment@2.10.6

warn Error on download for npm:react-bootstrap-datetimepicker
     Error: ENOENT, link '/Users/me/.jspm/packages/npm/react-bootstrap-datetimepicker@0.0.21/react-bootstrap-datetimepicker/lib/DateTimeField.js'
         at Error (native)

err  Error downloading npm:react-bootstrap-datetimepicker.

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
Thanks for posting. Yes this is a bug - fixed in https://github.com/jspm/npm/commit/d217afb04bd794bb9d65bcf07ed6be37d907d590, with release to follow in the next couple of days.

**Comment by fdhenard** [comment]
@guybedford.  Great! Thanks.

**Comment by guybedford** [comment]
This was published in 0.23.3.

**Comment by fdhenard** [comment]
> This was published in 0.23.3.

Is that the right version number?  This guy reported it working in 0.16.3:  http://stackoverflow.com/a/33438469/59439

**Comment by jbnv** [comment]
I'm still having this problem with the `firebase` module. Just ran `nom update jspm` to make sure I had the lasted version.

**Comment by guybedford** [comment]
@jbnv I just tried `jspm install firebase && jspm install npm:firebase` in both 0.16 and 0.16 and wasn't able to replicate.
